In [3]:
import numpy as np
import matplotlib as plt
import pandas as pd

In [16]:
# uploading necessary dataset from a website
iris = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
headernames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

In [20]:
#reading the dataset to panda dataframes
dataset = pd.read_csv(iris,names=headernames)
dataset.head()

sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [21]:
#completing the data processing:
#this function enables the model to select a particular cell of the dataset.
x=dataset.iloc[:, :-1].values
y=dataset.iloc[:,4].values

In [24]:
#splitting the data into train and test
#this function will split the 60% of data for training and 40% of data to testing
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.4)

In [29]:
#Scaling the data: normalizing data withing a particular range to make data easy to be learned and understood
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform (x_train)
x_test=scaler.transform(x_test)

In [30]:
#training the model with KNeighborClassifier
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=8)
classifier.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=8)

In [31]:
#make predictions
y_pred = classifier.predict(x_test)

In [37]:
#printing out the results
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print('RESULT', '\n', result)
result2 = classification_report(y_test, y_pred)
print('\n','RESULT2', '\n', result2)
result3 = accuracy_score(y_test, y_pred)
print('\n','RESULT3', '\n', result3)

RESULT 
 [[15  0  0]
 [ 0 22  1]
 [ 0  2 20]]

 RESULT2 
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        15
Iris-versicolor       0.92      0.96      0.94        23
 Iris-virginica       0.95      0.91      0.93        22

       accuracy                           0.95        60
      macro avg       0.96      0.96      0.96        60
   weighted avg       0.95      0.95      0.95        60


 RESULT3 
 0.95
